name: CIFuzz
on: [pull_request]
jobs:
 Fuzzing:
   runs-on: ubuntu-latest-large
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address]
   steps:
   - name: Build Fuzzers (${{ matrix.sanitizer }})
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@8dd2d8098817f9629a60ffb484e9596514ee5525  # master
     with:
       oss-fuzz-project-name: 'go-sqlite3'
       dry-run: false
       sanitizer: ${{ matrix.sanitizer }}
   - name: Run Fuzzers (${{ matrix.sanitizer }})
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@8dd2d8098817f9629a60ffb484e9596514ee5525  # master
     with:
       oss-fuzz-project-name: 'go-sqlite3'
       fuzz-seconds: 600
       dry-run: false
       sanitizer: ${{ matrix.sanitizer }}
   - name: Upload Crash
     uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5  # v1
     if: failure()
     with:
       name: ${{ matrix.sanitizer }}-artifacts
       path: ./out/artifacts
